version: "3.6"
services:

  onestep:
    depends_on:
      - mariadb
    image: dakalab/onestep
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: onestep
    hostname: onestep
    volumes:
      - ".:/app"
      - "./init.sh:/scripts/init.sh"
      - "./certs:/etc/nginx/certs"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=hello123
    ports:
      - "8080:80"
    networks:
      - backend

  mariadb:
    image: mariadb:10.4
    restart: unless-stopped
    container_name: mariadb
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hello123
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - backend

networks:
  backend:
    external:
      name: backend

volumes:
  mariadb_data:
